### ISSUE TITLE
data preprocessing, Convert BGR and RGB

### ISSUE THREAD

**Issue by terarachang** [Maluuba/GeNeVA#5]
Hi,

This is a very minor issue.  
(If I understand correctly, the background images are only used at the very first time step.)

Why not converting BGR to RGB in
https://github.com/Maluuba/GeNeVA/blob/master/geneva/data/codraw_dataset.py#L19 , 
as you have done in
https://github.com/Maluuba/GeNeVA/blob/master/geneva/data/codraw_dataset.py#L72 ?

Thanks!

**Comment by kracwarlock** [comment]
the first link is doing HWC -> CHW (channel, height, width) format conversion
while the second one is doing inversion within the last dimension (channels) so that one does BGR <-> RGB conversion

**Comment by terarachang** [comment]
Yes, I understand that. 
I'm asking why not also applying BGR <-> RGB conversion to the background image (L19), like:
```
f['background'].value[..., ::-1].transpose(2, 0, 1)
```
I've run the code and it seems that when the background image is forwarded to the model, it's still in BGR.
Thanks!

**Comment by kracwarlock** [comment]
ah so I will have to verify that when I get time but yes if that is the case this is a bug in the code and needs to be fixed. thanks for finding this out!
